const Colors = {
  LIGHT_GRAY: "#F8F8F8",
  PLACEHOLDER: "#D2D2D2", 
  CLICKABLE_PRIMARY_BG: "#004CFF",
  CLICKABLE_PRIMARY_TEXT: "#F3F3F3",
  CLICKABLE_DISABLED: "#D9E4FF",
  MODAL_HEADER: "#F8FAFF",
};

export default Colors;
